name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn --cwd packages/hardhat test

      - name: Deploy to Base Sepolia
        run: yarn --cwd packages/hardhat deploy --network baseSepolia
        env:
          __RUNTIME_DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      - name: Verify contracts
        run: |
          yarn --cwd packages/hardhat hardhat verify --network baseSepolia 0x2D55272e6Af67F33e52b63ee8384CDC61a044940
          yarn --cwd packages/hardhat hardhat verify --network baseSepolia 0x71FC62eF75779B773E0b74eA467C24B229066262 0x2D55272e6Af67F33e52b63ee8384CDC61a044940
          yarn --cwd packages/hardhat hardhat verify --network baseSepolia 0xb5EB13cd8408B6cE0D4829Ad5C312f9450Ac9db2 0x71FC62eF75779B773E0b74eA467C24B229066262 0x2D55272e6Af67F33e52b63ee8384CDC61a044940
          yarn --cwd packages/hardhat hardhat verify --network baseSepolia 0x56adc737758Dac8dC0C53dE7D5cF92eFE0d07C96 0x71FC62eF75779B773E0b74eA467C24B229066262 0x2D55272e6Af67F33e52b63ee8384CDC61a044940
        env:
          ETHERSCAN_V2_API_KEY: ${{ secrets.BASESCAN_API_KEY }}

  deploy-frontend:
    needs: deploy-contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Next.js
        run: yarn --cwd packages/nextjs build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: packages/nextjs
          vercel-args: --prod